### ISSUE TITLE
Link to Galeria-Kaufhof/pillar fork / joint development

### ISSUE THREAD

**Issue by magro** [comeara/pillar#31]
Because the https://github.com/Galeria-Kaufhof/pillar fork seems to be more actively maintained it would be nice to publicly mention this fork in the readme. Or even better join forces and share project maintenance / development, release management etc.

**Comment by comeara** [comment]
Thanks for bringing this up @magro. I've been interacting with @manuelkiessling on Twitter. He's offered to make the Galeria-Kaufhof the canonical Pillar. I've been considering his offer.

As I considered his offer, I came to a couple of conclusions and want to share those. I realize I

* Neglected Pillar and made commitments to review PRs I couldn't keep. I should have been more honest with myself and others about the time I had available to dedicate to the project
* Would like to remain involved if possible. I enjoy keeping track of Cassandra and Scala even though I no longer use those technologies in my day job
* Am in a personal and career situation where I can realistically spend some time on the project

So, let's discuss the state of the project and suggestions for moving forward.

**Comment by comeara** [comment]
Mentioned Galeria-Kaufhof fork in ab2b8a0.

**Comment by magro** [comment]
Awesome, thanks a lot for your open statement! I'd suggest to discuss via gitter how to proceed - https://gitter.im/Galeria-Kaufhof/pillar. WDYT?

**Comment by comeara** [comment]
Sounds good. See you at Gitter.

**Comment by comeara** [comment]
This discussion was moved to Gitter.
